const path = require('path');

// Set up auto reload to reload the process when any main files change
console.log('Will auto reload main process on file change');
require('electron-reload')(__dirname, {
    electron: path.join(process.cwd(), 'node_modules', '.bin', 'electron')
});

// Load the bundle generated by the build process
require('./main.bundle.js');
