const path = require('path');

// Set up auto reload to reload the window when files change
console.log('[main index.js] Will auto reload window on file change via electron-reload');
require('electron-reload')(__dirname, {
    electron: path.join(process.cwd(), 'node_modules', '.bin', 'electron')
});

// Load the bundle generated by the build process
require('./main.bundle.js');
